companieshouse/officer-filing-api

- pom.xml
- src/main/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImpl.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/error/ApiErrors.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/error/CachingFilter.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/error/ErrorType.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/error/InvalidFilingException.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/error/LocationType.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/error/RestExceptionHandler.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/OfficerFilingApiApplicationTests.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplIT.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplTest.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/error/RestExceptionHandlerTest.java
- add RestExceptionHandler and support types
- add handling for error types when they occur:
- JSON not readable
- data validation errors (TBD)
- Transaction service failures
- internal server error
- other errors (catch-all)
- increase unit and integration test coverage
Resolves:
DACT-129
> Produce consistent error message format

- routes.yaml
- src/main/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImpl.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/controller/ValidationStatusController.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/controller/ValidationStatusControllerImpl.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/exception/NotImplementedException.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/exception/ResourceNotFoundException.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/model/entity/Links.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/service/TransactionServiceImpl.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplTest.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/controller/ValidationStatusControllerImplIT.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/controller/ValidationStatusControllerImplTest.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/controller/ValidationStatusControllerTest.java
This is the bare bones of a `validation_status` endpoint.  The actual validation to be added in later story.  This is part of allowing the transaction to proceed to CHIPS.
Response:
```
{
"is_valid": true
}
```
DACT-127
needs docker-chs-dev change here: https://github.com/companieshouse/docker-chs-development/pull/538
> Add outline of validation controller

- src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerTerminationValidator.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplValidationIT.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/service/CompanyProfileServiceImplTest.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerTerminationValidatorTest.java
Validate that company has not been dissolved or in the process of being dissolved
- **As** Companies House
- **I want** users to be prevented from filing for the removal of a director who has already had a removal filed against them which has not yet been completed 
- **So that** the original termination date is the one that is persisted and the system does not get in a state
> DACT-249 Validate that company has not been dissolved

- src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerTerminationValidator.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerTerminationValidatorTest.java
Error message fix for companies with cessation date and/or dissolved status: only one of these errors should be returned. If a company has both a cessation date and a dissolved status, only the error case for a dissolved company should be shown.
> DACT-249: Validation error fix for dissolved company

- src/main/java/uk/gov/companieshouse/officerfiling/api/utils/LogHelper.java
LogMap was previously made immutable as a builder was introduced to populate the fields. I forgot that when this logMap is sent to structured-logging, more fields will be added at that point which caused the system to fall over.
> DACT-288 Undo immutable logMap

- src/main/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImpl.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/controller/ValidationStatusController.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/controller/ValidationStatusControllerImpl.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/model/mapper/ErrorMapper.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplIT.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplTest.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/controller/ValidationStatusControllerImplIT.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/controller/ValidationStatusControllerImplTest.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/controller/ValidationStatusControllerTest.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/model/mapper/ErrorMapperTest.java
We need a validation endpoint that the Software filer can use when they are using the Patch flow of submissions. Additionally, the same endpoint is used by the Transactions API to validate pre closing the transaction. 
Acceptance Criteria
Create a single endpoint that can be called by Transactions API and S/W filer. 
By doing so, this will help us to test the main acceptance criteria in the overall parent story around patching and validation rules.
GET /transactions/{transaction_id}/officers/{filing_resource_id}/validation_status
This will need to run all the validation that we have currently set up to run on the post endpoint.
Runs all validation for everything we’ve done for POST submissions already - call off to existing validation that is implemented. Will need to validate correct …
> Dact 354 create validation endpoint

- src/main/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImpl.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/exception/CompanyProfileServiceException.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/exception/ServiceUnavailableException.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/model/mapper/ErrorMapper.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/service/CompanyAppointmentService.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/service/CompanyAppointmentServiceImpl.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/service/CompanyProfileService.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/service/CompanyProfileServiceImpl.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerTerminationValidator.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplValidationIT.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/controller/ValidationStatusControllerImplIT.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/controller/ValidationStatusControllerImplTest.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/service/CompanyAppointmentServiceImplTest.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/service/CompanyProfileServiceImplTest.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerTerminationValidatorTest.java
Context: It was mentioned in a dev standup that we may need an error message if the company appointments api or public api is down Richard Walrond confirmed with Mike Moore and Joe Simons that an error message will be needed and we will need to block applications from progressing. There is a SLA of 99.9% uptime on API’s. 
As companies house
I want to stop software filers from filing a director removal request if the Company Appointments api or Public api is down
So that CHIPs is not overloaded with submissions to process that could potentially cause a data error.
https://companieshouse.atlassian.net/jira/software/c/projects/DACT/boards/477/backlog?view=detail&selectedIssue=DACT-328&issueLimit=100
Officer Filing VALIDATION TEST ONLY ADDED FOR THE CURRENT IMPLEMENTATION. Post validation to …
> Dact 328 services unavailable

- pom.xml
- src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerTerminationValidator.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerTerminationValidatorTest.java
Context: If the appointed date is prior to 1992 we need to check the field appointed-before otherwise the API will be looking in the wrong place and the API will fall over.
If the appointment date is prior to 1992 then we need to use the Appointment-before field to get the appointment date.
If the appointment date is post/including 1992 onwards then we need to use the ‘appointment-on’ field to get the appointment date.
https://companieshouse.atlassian.net/browse/DACT-336
> DACT-336: Allow submission with pre 1992 appointment date

- src/main/java/uk/gov/companieshouse/officerfiling/api/service/CompanyProfileService.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerTerminationValidator.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/controller/ValidationStatusControllerImplIT.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerTerminationValidatorTest.java
**As** companies house
**I want** the submission to be processed by CHIPS even if the data comes back null
**So that** it does not error up-front as it will not be clear what needs to be corrected by the person who submitted the removal request
There is also fail-early validation done on the transaction object but this should never be hit in a real-world situation.
> Handle null fields during validation

- README.md
- routes.yaml
This PR changes the healthcheck URL to avoid a clash with thunderbirds.
Goes with https://github.com/companieshouse/chs-configs/pull/2142
> feat: update healthcheck route

- routes.yaml
This PR makes routes.yaml less specific about /officer-filing to allow all actuator endpoints to work
> fix: health route

- pom.xml
- src/main/java/uk/gov/companieshouse/officerfiling/api/config/AppConfig.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImpl.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImplTest.java
When a director removal submission is made by a software filer using our Officer Filing API or via Web service, then the expectation is that the user would receive an email confirmation to indicate that their director removal submission was received.
This email should include the company upon which the director removal submission was made against, the date the submission was received, the reference number (if the user needs to contact customer service) and the filing type description.
Filing description:
https://companieshouse.atlassian.net/browse/DACT-407
> DACT-407-Include Filing Type name and description in the submission notification

- src/main/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImpl.java
Taking out the temporary logging that we added as it should no longer be needed as the issue was that the versions were not upping in the pipeline, so we had older code in staging to reserve2, which was why the description was missing.
> DACT-282: removing the temporary logging.

- src/main/java/uk/gov/companieshouse/officerfiling/api/controller/DirectorsController.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/controller/DirectorsControllerImpl.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/exception/OfficerServiceException.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/service/OfficerService.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/service/OfficerServiceImpl.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/controller/DirectorsControllerImplIT.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/controller/DirectorsControllerImplTest.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/controller/DirectorsControllerTest.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/service/OfficerServiceImplTest.java
The current directors page is the 6th page in the happy path journey for the web service. It acts as a page where an Officer may select from a list of active directors associated with a company to remove.
An Officer should be able to click the remove director link which will take them to the ‘When was this director removed ?’ (removal date) page.
To complete this work, we first need an endpoint to retrieve the list of active Directors.
> Dact 385 retrieve list of directors

- src/main/java/uk/gov/companieshouse/officerfiling/api/service/CompanyAppointmentServiceImpl.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/service/CompanyAppointmentServiceImplTest.java
[DACT-421](https://companieshouse.atlassian.net/browse/DACT-421)
An issue has been found when an invalid appointment ID is sent in a TM01. A service is down response is sent rather than an officer not found error. Discussed how we would handle with Thunderbirds and it was suggested that we make a change to our response body.
[DACT-421]: https://companieshouse.atlassian.net/browse/DACT-421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DACT-421 Differentiate company appointment 404 errors

- pom.xml
- src/main/java/uk/gov/companieshouse/officerfiling/api/controller/DirectorsControllerImpl.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImpl.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/model/filing/FilingResponse.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplIT.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplTest.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplValidationIT.java
**As** companies house 
**I want** Officer ID for the director I'm trying to be removed to be saved 
**So that** I am able to use the data on future pages and for validation
- Update java SDK to include self link on appointments. Referenced appointment ID can be extracted from this to be used when retrieving current active directors. 
- Add officer name to post response to be set on the web
[DACT-489](https://companieshouse.atlassian.net/browse/DACT-489)
[DACT-489]: https://companieshouse.atlassian.net/browse/DACT-489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DACT-489 Add self link to appointment and return name from TM01 post

- src/main/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImpl.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImplTest.java
Remove DOB requirement for corporate director filings
Issue occurred when a TM01 request was sent for a corporate director. The callback from the filing resource handler would fail. API would throw an exception trying to convert the non existent date to a date3tuple. Exception as seen in https://companieshouse.atlassian.net/browse/DACT-610.
Fix allows the filing resource handler to return as expected.
> Remove DOB requirement for corporate director filings

- src/main/java/uk/gov/companieshouse/officerfiling/api/service/OfficerServiceImpl.java
The active directors page should now show one hundred entries. Five per page with twenty pages.
taf-api-karate branch DACT-439_pagination_testing has a feature file named insert_directors.feature which can be run to add the required directors.
> DACT-503: Pagination up to 100 directors

- src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerTerminationValidator.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerTerminationValidatorTest.java
As companies house 
I want to make sure that the correct companies can file a TM01, CH01 and AP01
So that officers filing for a TM01, CH01 and AP01 that are only of the correct company type
Acceptance Criteria: 
AC1: For the both API and Web we should be allowing the following Company types; 
"private-unlimited", 
"ltd", 
"plc",
"private-limited-guarant-nsc-limited-exemption",
"private-limited-guarant-nsc", 
"private-unlimited-nsc", 
"private-limited-shares-section-30-exemption"
> DACT-570-Update-Allowed-Companies

- src/main/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImpl.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/model/dto/OfficerFilingDto.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/model/entity/OfficerFiling.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/model/entity/OfficerFilingData.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/model/mapper/OfficerFilingMapper.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplTest.java
Currently officer filing dto accepts name as a single field. This has been split into 3 separate fields and needs to be reflected in the api.
[DACT-341](https://companieshouse.atlassian.net/browse/DACT-341)
[DACT-341]: https://companieshouse.atlassian.net/browse/DACT-341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DACT-341 Add first middle and last names to filing dto

- src/main/java/uk/gov/companieshouse/officerfiling/api/enumerations/ValidationEnum.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerAppointmentValidator.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerAppointmnetValidatorTest.java
Add validation for a directors occupation.
Occupation is an optional field and should be less than 100 characters in length. Should follow charset 2 as referenced at https://companieshouse.atlassian.net/browse/DACT-707
> Dact 707 directors occupation

- src/main/java/uk/gov/companieshouse/officerfiling/api/enumerations/ValidationEnum.java
- src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerAppointmentValidator.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerAppointmentValidatorTest.java
AC1 for residential address and correspondence Address
**Postcode is a mandatory field when**
- No country is entered (or no data is entered)
- When a British country, england, scotland etc is entered .
**It only becomes optional when:**
- A non british country is entered.
> DACT-739 Updated postcode validation

- src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerAppointmentValidator.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerAppointmentValidatorTest.java
https://companieshouse.atlassian.net/browse/DACT-1657
Skipping duplicate validation checks on linked addresses if SameAs flags are set, as the linked to address will have already been validated.
> DACT-1657: Skip address validation if sameAs flags are set

- pom.xml
- src/main/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImpl.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImplTest.java
* Director names should be capitalised.
* Director names should include title and middle name if provided.
* Fix for CH01 director name in email contains null if middle name is absent in the appointment.
* Corporate director name should be capitalised if not already in the appointment.
> DACT-1639 TM01, AP01, CH01 name formatting fixes in director names.

- src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerValidator.java
- src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerValidatorTest.java
JIRA bug: https://companieshouse.atlassian.net/browse/DACT-1911
Fix nationality length validation to not assume nationality3 is empty if nationality2 is.
> bugfix/DACT-1911 Nationality length check when nationality2 is empty but nationality3 present.
