src/test/resources/application.properties
same as in main, but set to DEBUG
=> adding test app.props for build in pipline to run

start.sh
=> adding start file for e2e build

src/main/java/uk/gov/companieshouse/officerfiling/api/model/dto/OfficerFilingDto.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/entity/OfficerFiling.java, src/test/java/uk/gov/companieshouse/officerfiling/api/model/mapper/OfficerFilingMapperTest.java
=> Rename ETag to Etag in properties

pom.xml, src/main/java/uk/gov/companieshouse/officerfiling/api/OfficerFilingApiApplication.java, src/main/java/uk/gov/companieshouse/officerfiling/api/config/AppConfig.java, src/main/java/uk/gov/companieshouse/officerfiling/api/config/LoggingConfig.java, src/main/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingController.java, src/main/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImpl.java, src/main/java/uk/gov/companieshouse/officerfiling/api/exception/TransactionServiceException.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/entity/Date3Tuple.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/entity/FormerName.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/entity/Identification.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/entity/Links.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/mapper/OfficerFilingMapper.java, src/main/java/uk/gov/companieshouse/officerfiling/api/service/ApiClientService.java, src/main/java/uk/gov/companieshouse/officerfiling/api/service/ApiClientServiceImpl.java, src/main/java/uk/gov/companieshouse/officerfiling/api/service/OfficerFilingServiceImpl.java, src/main/java/uk/gov/companieshouse/officerfiling/api/service/TransactionService.java, src/main/java/uk/gov/companieshouse/officerfiling/api/service/TransactionServiceImpl.java, src/main/resources/logger.properties, src/test/java/uk/gov/companieshouse/officerfiling/api/OfficerFilingApiApplicationTests.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplIT.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/model/mapper/OfficerFilingMapperTest.java
POST request handling
- Add Transaction Resources to the parent transaction including links to the created filing resource
- Add corresponding links to the created officer filing resource
- Successful path only; no specific errors handled yet, e.g. transaction does not exist
=> Add reference to TM01 data to TM01 transaction

src/main/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingController.java, src/main/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImpl.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/dto/AddressDto.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/dto/OfficerFilingDto.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/entity/Address.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/entity/Links.java, src/main/java/uk/gov/companieshouse/officerfiling/api/service/OfficerFilingService.java, src/main/java/uk/gov/companieshouse/officerfiling/api/service/OfficerFilingServiceImpl.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplIT.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerTest.java
https://companieshouse.atlassian.net/browse/DACT-126
=> Resolves: DACT-126

src/test/java/uk/gov/companieshouse/officerfiling/api/service/TransactionServiceImplTest.java
tests for `getTransaction` and `updateTransaction` to improve overall coverage.
=> Add unit test for coverage of TransactionService

src/main/java/uk/gov/companieshouse/officerfiling/api/model/entity/OfficerFiling.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/filing/FilingData.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/mapper/OfficerFilingMapper.java, src/main/java/uk/gov/companieshouse/officerfiling/api/service/FilingServiceImpl.java, src/test/java/uk/gov/companieshouse/officerfiling/api/service/FilingServiceImplTest.java
- first and last name and date of birth
- see consumer PR https://github.com/companieshouse/chips-filing-consumer/pull/185
DACT-175
=> Pass dummy in filing data to CHIPS consumer

src/main/java/uk/gov/companieshouse/officerfiling/api/model/dto/OfficerFilingDto.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/entity/OfficerFiling.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplIT.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingDataControllerImplIT.java, src/test/java/uk/gov/companieshouse/officerfiling/api/model/mapper/OfficerFilingMapperTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/service/FilingServiceImplTest.java
As discussed and agreed with architect.
Change has been made already to the Data Model design
so submitted json will now be:
```"reference_appointment_id": "456"```
DACT-176
=> Rename 'referenceOfficerId' to 'referenceAppointmentId' and associated json

Tiltfile.dev, src/main/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImpl.java
Please check with test before approving this as it will re-enable the TM01 endpoint
=> Default enable tm01 dact 294

CODEOWNERS
Added thundercats as reviewers for this repository
=> Created codeowners file to enable PR rules for repo

src/main/java/uk/gov/companieshouse/officerfiling/api/controller/FilingDataControllerImpl.java, src/main/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImpl.java, src/main/java/uk/gov/companieshouse/officerfiling/api/controller/ValidationStatusControllerImpl.java, src/main/java/uk/gov/companieshouse/officerfiling/api/error/RestExceptionHandler.java, src/main/java/uk/gov/companieshouse/officerfiling/api/service/CompanyAppointmentService.java, src/main/java/uk/gov/companieshouse/officerfiling/api/service/CompanyAppointmentServiceImpl.java, src/main/java/uk/gov/companieshouse/officerfiling/api/service/CompanyProfileServiceImpl.java, src/main/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImpl.java, src/main/java/uk/gov/companieshouse/officerfiling/api/service/OfficerFilingServiceImpl.java, src/main/java/uk/gov/companieshouse/officerfiling/api/service/TransactionServiceImpl.java, src/main/java/uk/gov/companieshouse/officerfiling/api/utils/LogHelper.java, src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerTerminationValidator.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplIT.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplValidationIT.java, src/test/java/uk/gov/companieshouse/officerfiling/api/service/CompanyAppointmentServiceImplTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImplTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerTerminationValidatorTest.java
Context: This relates to the Officer Filing API. This story relates to the work that Companies Houses did prior to the handover. We need to refactor their code so that logging meets CH standards. 
For more information on Structured Logging - [Structured logging - Dept: Development - Confluence (atlassian.net)](https://companieshouse.atlassian.net/wiki/spaces/DEV/pages/1455390722/Structured+logging)
**As** Companies House Support,
**I want** Companies House logging standards to be followed,
**So that** we have consistent logging and reporting across our services.
https://companieshouse.atlassian.net/browse/DACT-288
=> DACT-288 Implement Structured Logging

src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerTerminationValidator.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplIT.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplValidationIT.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerTerminationValidatorTest.java
**As** Companies House
**I want** users from specific company types to be prevented from filing for the removal of a director
**So** that I only receive submissions for companies that are allowed to file a TM01 request
https://companieshouse.atlassian.net/browse/DACT-285
=> DACT-285 validate company type

src/main/java/uk/gov/companieshouse/officerfiling/api/model/entity/OfficerFiling.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/filing/FilingData.java, src/main/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImpl.java, src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerTerminationValidator.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplIT.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplValidationIT.java, src/test/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImplTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerTerminationValidatorTest.java
Context: This story relates to passing in a corporate director flag so that CHIPS can process the removal of corporate director.  
**As** Companies House
**I want** to know whether a director being removed is an individual director or Corporate Director
**So that** we can Reject the submission to remove anyone that is not an individual director or Corporate Director
https://companieshouse.atlassian.net/browse/DACT-334
=> DACT-334 Validate Corporate or Individual Directors

routes.yaml, src/main/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingController.java, src/main/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImpl.java, src/main/java/uk/gov/companieshouse/officerfiling/api/exception/OfficerFilingServiceException.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/dto/OfficerFilingDto.java, src/main/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImpl.java, src/main/java/uk/gov/companieshouse/officerfiling/api/service/OfficerFilingService.java, src/main/java/uk/gov/companieshouse/officerfiling/api/service/OfficerFilingServiceImpl.java, src/main/java/uk/gov/companieshouse/officerfiling/api/service/TransactionServiceImpl.java, src/main/java/uk/gov/companieshouse/officerfiling/api/utils/MapHelper.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplIT.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplValidationIT.java, src/test/java/uk/gov/companieshouse/officerfiling/api/service/OfficerFilingDataServiceImplTest.java
https://companieshouse.atlassian.net/browse/DACT-348
PR to add a patch URL for building TM01 filings.
=> Dact 279 add patch url

src/main/java/uk/gov/companieshouse/officerfiling/api/config/InterceptorConfig.java, src/main/java/uk/gov/companieshouse/officerfiling/api/controller/ValidationStatusControllerImpl.java, src/main/java/uk/gov/companieshouse/officerfiling/api/interceptor/RequestLoggingInterceptor.java, src/test/java/uk/gov/companieshouse/officerfiling/api/interceptor/RequestLoggingInterceptorTest.java
This requirement was flagged during a peer review of the Structured Logging refactor we helped implement for Companies House with Joanne Simons. It will also help to ensure Companies House can monitor and alert on Officer Filing API issues. 
We need to ensure we capture when a request comes so we can log the start and end of a call so Companies House can eventually setup an alert to measure how long a call to the Officer API takes.
=> Logging interceptor created

src/main/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImpl.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplIT.java
https://companieshouse.atlassian.net/browse/DACT-371
Return the filingId in response body to avoid having to parse it from the Location header.
=> Dact 371 return filing id in post body

src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerTerminationValidator.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerTerminationValidatorTest.java
https://companieshouse.atlassian.net/browse/DACT-379
Validate that ETAG, Officer ID, and Termination date data coming in via software filer is not null.
=> DACT-379: Null point checking on input fields

.gitmodules, Makefile, README.md, src/main/java/uk/gov/companieshouse/officerfiling/api/config/enumerations/ConstantsEnumerationsConfig.java, src/main/java/uk/gov/companieshouse/officerfiling/api/config/enumerations/OfficerFilingEnumerationsConfig.java, src/main/java/uk/gov/companieshouse/officerfiling/api/controller/ValidationStatusControllerImpl.java, src/main/java/uk/gov/companieshouse/officerfiling/api/enumerations/ApiEnumerations.java, src/main/java/uk/gov/companieshouse/officerfiling/api/enumerations/ValidationEnum.java, src/main/java/uk/gov/companieshouse/officerfiling/api/enumerations/YamlPropertySourceFactory.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/dto/OfficerFilingDto.java, src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerTerminationValidator.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplIT.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplValidationIT.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/ValidationStatusControllerImplIT.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/ValidationStatusControllerImplTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/enumerations/ApiEnumerationsTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/enumerations/ConstantsConfigTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/enumerations/OfficerFilingEnumerationsConfigTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerTerminationValidatorTest.java
Clean-up task needed prior to private beta release to ensure the error messages are updated with Companies House approval. These messages are stored within api-enumerations.
=> DACT-342 Update error messages to use api-enumerations

src/main/java/uk/gov/companieshouse/officerfiling/api/controller/DirectorsController.java, src/main/java/uk/gov/companieshouse/officerfiling/api/controller/DirectorsControllerImpl.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/DirectorsControllerImplIT.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/DirectorsControllerImplTest.java
https://companieshouse.atlassian.net/browse/DACT-387
add endpoint for retrieving TM01 check your answers details. Add associated unit tests
=> DACT-387 : add endpoint for retrieving TM01 check your answers details

src/main/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImpl.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/filing/FilingResponse.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/DirectorsControllerImplTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplIT.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplTest.java
Don't return name in a filing response as it's now looked up by the web app
=> Dact 532 invalid appointment id bug

src/main/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImpl.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplIT.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplTest.java
Check if we already have a filing for a transaction on POST. If we do, reuse it
=> Check if we already have a filing for a transaction on POST. If we do, reuse it

pom.xml
Small change highlighted in show and tell by CH (not captured in the prototype).
We currently return the directors name dynamically to show Surname, First name in the Date of Remove and Check your answers page which matches the format on the current directors page. The request is to update this to show the individual company director’s name in the following format - First name, Middle name, Surname - on the date of remove and check your answers page.
If middle name is not present then just show First name, Surname format.
For instance,
We need to show the following: Kathryn Rebecca Davies INSTEAD of DAVIES, Kathryn Rebecca
Andrew Murray INSTEAD of MURRAY, Andrew
https://companieshouse.atlassian.net/browse/DACT-557
=> DACT-557-Update-Private-SDK

src/main/java/uk/gov/companieshouse/officerfiling/api/interceptor/OfficersCRUDAuthenticationInterceptor.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/DirectorsControllerImplIT.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplIT.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplValidationIT.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/ValidationStatusControllerImplIT.java
https://companieshouse.atlassian.net/browse/DACT-659
Check a the create token permission is set for an AP01
=> DACT-659: Update token permission interceptor

src/test/java/uk/gov/companieshouse/officerfiling/api/controller/ValidationStatusControllerImplTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImplTest.java
i switched exeption class to be notImplimentedException, which is more accurate as its an error until we have implimented Change CHo1,  but i forgot to alter the tests which were expecting the old exception still.
=> DACT-558 - fixing 2 tests

src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerValidator.java
Updated reg ex requirements for single line input
=> Update reg ex from new requirements

src/main/java/uk/gov/companieshouse/officerfiling/api/enumerations/ValidationEnum.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/entity/Date3Tuple.java, src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerAppointmentValidator.java, src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerValidator.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/ValidationStatusControllerImplTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerAppointmnetValidatorTest.java
https://companieshouse.atlassian.net/browse/DACT-696
Date of birth field is now mandatory and will be validated.
Date of birth must be at least 16
Date of birth must be under 110
=> Dact 696 directors dob

src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerAppointmentValidator.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerAppointmentValidatorTest.java
Adding a missed validation check for director age on appointment date
=> DACT-638: Added validation of director age on appointment date

src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerAppointmentValidator.java, src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerValidator.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerAppointmentValidatorTest.java
we missed the fact that BRITISH could be sent in and that was not found as the list contained British.  Fine for the drop down list front end but the software filers could send in anything.
=> DACT-561 altering list check so that case is irrelevant

spec/swagger.json, src/main/java/uk/gov/companieshouse/officerfiling/api/model/dto/OfficerFilingDto.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/entity/OfficerFiling.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/entity/OfficerFilingData.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/mapper/OfficerFilingMapper.java, src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerAppointmentValidator.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/ValidationStatusControllerImplTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/model/mapper/OfficerFilingMapperTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/service/OfficerFilingDataServiceImplTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerAppointmentValidatorTest.java
Refactored DTO to reflect serviceAddress instead of address.
=> DACT-739 validate Directors' service address.

src/main/java/uk/gov/companieshouse/officerfiling/api/enumerations/ValidationEnum.java, src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerAppointmentValidator.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerAppointmentValidatorTest.java
Added separate error message for validation check of directors age on appointment vs age today
=> DACT-910: Update underage director appointment error

src/main/java/uk/gov/companieshouse/officerfiling/api/model/entity/OfficerFilingData.java
there was an extra `s` in serviceAddressBackLink
=> DACT-706 address the typo for serviceAddressbackLink

src/main/java/uk/gov/companieshouse/officerfiling/api/model/dto/OfficerFilingDto.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/entity/OfficerFiling.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/entity/OfficerFilingData.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/mapper/OfficerFilingMapper.java, src/test/java/uk/gov/companieshouse/officerfiling/api/model/mapper/OfficerFilingMapperTest.java
https://companieshouse.atlassian.net/browse/DACT-1004
API changes required for back link navigation from protected details page
=> DACT-1004: Protected details back link navigation

src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerAppointmentValidator.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerAppointmentValidatorTest.java
* Country validation should be case-insensitive
* Mandatory postcode validation for UK countries with case insensitivity.
=> DACT-1083 validation fixes for api for country and postcode

src/main/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImpl.java, src/test/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImplTest.java
https://companieshouse.atlassian.net/browse/DACT-1239
OFFICER_FILING_DESCRIPTION is not currently set in any env variables so no need to update them with the name change
=> DACT-1239 Chips Filing Description for AP01

src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerAppointmentValidatorTest.java
https://companieshouse.atlassian.net/browse/DACT-914
Using updated api-enumerations in tests
=> Update to nationality error tests

src/main/java/uk/gov/companieshouse/officerfiling/api/error/RestExceptionHandler.java, src/test/java/uk/gov/companieshouse/officerfiling/api/error/RestExceptionHandlerTest.java
conditionally add location, as null values can lead to unclear results as the response.
=> DACT-1026 

src/main/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImpl.java, src/test/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImplTest.java
Use resignation and appointment date instead of current date
=> DACT-1239 Update date used in CHIPS filing descriptions

src/main/java/uk/gov/companieshouse/officerfiling/api/model/dto/OfficerFilingDto.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/entity/OfficerFilingData.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/mapper/OfficerFilingMapper.java, src/test/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImplTest.java
https://companieshouse.atlassian.net/browse/DACT-1482
has_been_updated are to show whether the user has updated that section of information during CH01 web journey
=> DACT-1482 Add CH01 has been updated booleans

src/main/java/uk/gov/companieshouse/officerfiling/api/interceptor/OfficersCRUDAuthenticationInterceptor.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/DirectorsControllerImplIT.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplIT.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplValidationIT.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/ValidationStatusControllerImplIT.java
https://companieshouse.atlassian.net/browse/DACT-964 - Adding CH01 permissions
=> DACT-964: Adding CH01 permissions

src/main/java/uk/gov/companieshouse/officerfiling/api/model/dto/OfficerFilingDto.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/entity/OfficerFiling.java, src/main/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImpl.java, src/test/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImplTest.java
https://companieshouse.atlassian.net/browse/DACT-1488
Add name fields based on the nameHasBeenUpdated boolean in the filing
=> DACT-1488 Get officers name when creating CHIPS JSON

src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerAppointmentValidator.java, src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerUpdateValidator.java, src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerValidator.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerUpdateValidatorTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerValidatorTest.java
* Refactored the structuring by moving the methods to superclass for centralised implementation of validation methods between AP01 and CH01.
* NPE fix for appointment date check for the date of change validation.
=> DACT-1734 Defect/Bug fixes

src/main/java/uk/gov/companieshouse/officerfiling/api/controller/ValidationStatusControllerImpl.java, src/main/java/uk/gov/companieshouse/officerfiling/api/enumerations/ValidationEnum.java, src/main/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImpl.java, src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerAppointmentValidator.java, src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerTerminationValidator.java, src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerUpdateValidator.java, src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerValidator.java, src/test/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImplTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerAppointmentValidatorTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerTerminationValidatorTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerUpdateValidatorTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerValidatorTest.java
https://companieshouse.atlassian.net/browse/DACT-1489
=> DACT-1489 Nationality inclusion in chips json and api validation

src/main/java/uk/gov/companieshouse/officerfiling/api/config/InterceptorConfig.java, src/main/java/uk/gov/companieshouse/officerfiling/api/interceptor/OfficersCRUDAuthenticationInterceptor.java, src/test/java/uk/gov/companieshouse/officerfiling/api/OfficerFilingApiApplicationTests.java, src/test/java/uk/gov/companieshouse/officerfiling/api/interceptor/OfficersCRUDAuthenticationInterceptorTest.java
JIRA https://companieshouse.atlassian.net/browse/DACT-1702
Compare company number in scope against company number in transaction as part of officer filing CRUD interceptor.
=> dact-1702 check company number in scope against transaction

src/main/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImpl.java
JIRA https://companieshouse.atlassian.net/browse/DACT-1717
Tidy up some code smells that accumulated in SonarQube.
=> dact-1717 fix code smells

pom.xml, src/main/java/uk/gov/companieshouse/officerfiling/api/controller/ValidationStatusControllerImpl.java, src/main/java/uk/gov/companieshouse/officerfiling/api/enumerations/ValidationEnum.java, src/main/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImpl.java, src/main/java/uk/gov/companieshouse/officerfiling/api/validation/AddressValidator.java, src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerAppointmentValidator.java, src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerTerminationValidator.java, src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerUpdateValidator.java, src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerValidator.java, src/test/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImplTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerUpdateValidatorTest.java
https://companieshouse.atlassian.net/browse/DACT-1736
=> DACT-1736 build filing for correspondence address

src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerUpdateValidator.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerUpdateValidatorTest.java
https://companieshouse.atlassian.net/browse/DACT-1736
=> DACT-1736 Treat false and undefined link fields the same

src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerUpdateValidator.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerUpdateValidatorTest.java
https://companieshouse.atlassian.net/browse/DACT-1736
=> DACT-1736 Do not validate address if it is linked

src/main/java/uk/gov/companieshouse/officerfiling/api/enumerations/ValidationEnum.java, src/main/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImpl.java, src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerUpdateValidator.java, src/test/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImplTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerUpdateValidatorTest.java
https://companieshouse.atlassian.net/browse/DACT-1490
=> DACT-1490 Residential Address Validation and Build CHIPS Filing

src/main/java/uk/gov/companieshouse/officerfiling/api/controller/ValidationStatusControllerImpl.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/ValidationStatusControllerImplTest.java
update logic for feature checks featureNotEnabledException to avoid allowing anything as CH01 request.
=> DACT-1850 

src/main/java/uk/gov/companieshouse/officerfiling/api/enumerations/ValidationEnum.java, src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerUpdateValidator.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerUpdateValidatorTest.java
Also added missing name validation checks against chips data.
=> DACT-2075 Validate CH01 request to be non-empty. 

src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerUpdateValidator.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerUpdateValidatorTest.java
JIRA: https://companieshouse.atlassian.net/browse/DACT-1945
Adds validation to check for multiple same as flags being set
=> DACT-1945: Added validation for multiple address flags being set

src/main/java/uk/gov/companieshouse/officerfiling/api/config/InterceptorConfig.java, src/main/java/uk/gov/companieshouse/officerfiling/api/interceptor/ValidTransactionInterceptor.java, src/main/java/uk/gov/companieshouse/officerfiling/api/service/OfficerFilingService.java, src/main/java/uk/gov/companieshouse/officerfiling/api/service/OfficerFilingServiceImpl.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/ValidationStatusControllerImplIT.java, src/test/java/uk/gov/companieshouse/officerfiling/api/interceptor/ValidTransactionInterceptorTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/service/OfficerFilingDataServiceImplTest.java
JIRA https://companieshouse.atlassian.net/browse/DACT-2228
Extend endpoints covered by valid transaction interceptor.
Be more strict about an exact match not just "contains" expected.
=> dact-2228 extend interceptor

src/main/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImpl.java, src/test/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImplTest.java
https://companieshouse.atlassian.net/browse/DACT-2142
Include extra logic to cover certain edge cases when has_been_updated booleans have not been included
=> DACT-2142 Check existence of fields within sections

src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerAppointmentValidator.java, src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerValidator.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerValidatorTest.java
https://companieshouse.atlassian.net/browse/DACT-1341
=> DACT-1341: Fix Director's Name Allowing Numbers

src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerTerminationValidator.java, src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerUpdateValidator.java, src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerValidator.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerTerminationValidatorTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerUpdateValidatorTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerValidatorTest.java
https://companieshouse.atlassian.net/browse/DACT-2383
Add etag change validation to CH01
=> Add etag change validation to CH01

src/main/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingController.java, src/main/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImpl.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerImplTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/controller/OfficerFilingControllerTest.java
JIRA https://companieshouse.atlassian.net/browse/DACT-578
Checks that transaction is linked to filing.
=> dact-578 validate submission linked by transaction

src/main/java/uk/gov/companieshouse/officerfiling/api/model/dto/OfficerFilingDto.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/entity/OfficerFiling.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/entity/OfficerFilingData.java, src/main/java/uk/gov/companieshouse/officerfiling/api/model/mapper/OfficerFilingMapper.java, src/main/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImpl.java, src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerUpdateValidator.java, src/test/java/uk/gov/companieshouse/officerfiling/api/service/FilingDataServiceImplTest.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerUpdateValidatorTest.java
JIRA: https://companieshouse.atlassian.net/jira/software/c/projects/DACT/boards/492?selectedIssue=DACT-2180
Flag name change from correspondenceAddressHasBeenUpdated to serviceAddressHasBeenUpdated
=> DACT-2180: Flag changed to serviceAddressHasBeenUpdated

README.md
JIRA https://companieshouse.atlassian.net/browse/DACT-2485
=> dact-2485 edit api README

README.md
Jira: https://companieshouse.atlassian.net/browse/DACT-2511
=> DACT-2511: add config section to readme

src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerValidator.java, src/test/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerUpdateValidatorTest.java
Jira: https://companieshouse.atlassian.net/browse/DACT-2513
=> DACT-2513: allow . as valid title character

README.md
=> Add ecs to readme

terraform/groups/ecs-service/locals.tf, terraform/groups/ecs-service/main.tf, terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars, terraform/groups/ecs-service/variables.tf
**Jira ticket**: 
>
> Use screenshots or logs to show what your changes do.
>
> Add test notes only if they're **not** already included in the Jira ticket.
Strikethrough (`~~like this~~`) anything not applicable to your changes.
=> Tech debt changes

Makefile
remove security-check from MakeFile to fix pipeline.
**Jira ticket**: 
remove security-check from MakeFile to fix pipeline.
>
> Use screenshots or logs to show what your changes do.
>
> Add test notes only if they're **not** already included in the Jira ticket.
Strikethrough (`~~like this~~`) anything not applicable to your changes.
=> fix pipeline

pom.xml, src/main/java/uk/gov/companieshouse/officerfiling/api/interceptor/OfficersCRUDAuthenticationInterceptor.java, src/main/java/uk/gov/companieshouse/officerfiling/api/validation/AddressValidator.java, src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerUpdateValidator.java, src/main/java/uk/gov/companieshouse/officerfiling/api/validation/OfficerValidator.java
**Jira ticket**: ASM-276
- update dependency versions
- switch to `commons.lang3`
Please see PR for officer-filing-web  - https://github.com/companieshouse/officer-filing-web/pull/566
=> Update dependency versions
